kind: Deployment
apiVersion: apps/v1
metadata:
 namespace: default
 name: simple-react
spec:
  replicas: 3
  selector:
    matchLabels:
      app: simple-react
  
  template:
    metadata:
      labels:
        app: simple-react
    spec:
      containers:
        - name: simple-react
          image: europe-west3-docker.pkg.dev/vf-grp-vbitvtr-alpha/docker-fe-repo/simple-react:2.0
          imagePullPolicy: Always
          ports:
          - containerPort: 3000
            name: http
