kind: Namespace
apiVersion: v1
metadata:
  name: test
  labels:
    name: test
---
kind: Deployment
apiVersion: apps/v1
metadata:
 namespace: test
 name: simple-react
spec:
  selector:
    matchLabels:
      app: simple-react
  replicas: 3
  template:
    metadata:
      labels:
        app: simple-react
    spec:
      containers:
        - name: simple-react
          image: europe-west3-docker.pkg.dev/vf-grp-vbitvtr-alpha/docker-fe-repo/simple-react:2.1
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
 ---
 apiVersion: apps/v1
kind: Service
metadata:
  name: simple-react
spec:
  selector:
    app: simpe-react
  type: LoadBalancer
  ports:
  - port: 80
targetPort: 3000
