---
apiVersion: v1
kind: "Service"
metadata:
  name: "simple-react"
  namespace: "default"
spec:
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 3000
  selector:
    app: "simple-react"
  type: "LoadBalancer"
