apiVersion: apps/v1
kind: Service
metadata:
  namespace: test
  name: simple-react
spec:
  selector:
    app: simple-react
  namespace: test  
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
